ups_services = {
    "Next Day Air":"01",
    "2nd Day Air":"02",
    "Ground":"03",
    "Express":"07",
    "Expedited":"08",
    "UPS Standard":"11",
    "3 Day Select":"12",
    "Next Day Air Saver":"13",
    "Next Day Air Early A.M.":"14",
    "Express Plus":"54",
    "2nd Day Air A.M.":"59",
    "UPS Saver":"65"
}
ups_packages = {
    "UPS Letter":"01",
    "Customer Supplied Package":"02",
    "Tube":"03",
    "PAK":"04",
    "UPS Express Box":"21",
    "UPS 25KG Box":"24",
    "UPS 10KG Box":"25",
    "Pallet":"30",
    "Small Express Box":"2a",
    "Medium Express Box":"2b",
    "Large Express Box":"2c",
    "Flats":"56",
    "Parcels":"57",
    "BPM":"58",
    "First Class":"59",
    "Priority":"60",
    "Machinables":"61",
    "Irregulars":"62",
    "Parcel Post":"63",
    "BPM Parcel":"64",
    "Media Mail":"65",
    "BMP Flat":"66",
    "Standard Flat":"67"
}
